BCS-1067 Added pinned message support, migrate from synthetic
crafttalk/crafttalk-android-sdk pull request #51
Opened 2024-12-25 09:36 UTC by philipok2

2025-02-03 13:48 UTC, anclyakeks commented on app/src/androidTest/java/com/crafttalk/sampleChat/ChatTest.kt
Сделай задачу на написание тестов по рефакторингу

2025-02-04 16:47 UTC, Netlighter requested changes
в целом норм, рефакторинг понятен, только с логикой в некоторых местах поправить и все

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/presentation/ChatView.kt
> +                is DefaultMessageItem -> TODO()
что такое  TODO?

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/presentation/ChatView.kt
> +                binding.chatPlace.userFeedback.feedbackStar5.setImageResource(R.drawable.com_crafttalk_chat_ic_star)
это все шаблонный код, так что его можно оптимизировать. необязательно точь-в-точь но суть такая:

```kotlin
private fun giveFeedback(countStars: Int, isLastDecision: Boolean) {
    val stars = arrayOf(
        binding.chatPlace.userFeedback.feedbackStar1,
        binding.chatPlace.userFeedback.feedbackStar2,
        binding.chatPlace.userFeedback.feedbackStar3,
        binding.chatPlace.userFeedback.feedbackStar4,
        binding.chatPlace.userFeedback.feedbackStar5
    )

    stars.forEachIndexed { index, star ->
        star.setImageResource(
            if (index < countStars) R.drawable.com_crafttalk_chat_ic_star
            else R.drawable.com_crafttalk_chat_ic_star_outline
        )
    }

    if (isLastDecision) {
        binding.chatPlace.userFeedback.root.setOnTouchListener(null)
        viewModel.giveFeedbackOnOperator(countStars, null, viewModel.dialogID1)

        binding.chatPlace.userFeedback.root.delayOnLifecycle(ChatAttr.getInstance().delayFeedbackScreenAppears) {
            viewModel.feedbackContainerVisible.value = false

            // cброс всех звезд
            stars.forEach { star ->
                star.setImageResource(R.drawable.com_crafttalk_chat_ic_star_outline)
            }

            setFeedbackListener()
        }
    }
}
```

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/presentation/feature/pined_message_viewer/PinedMessageModel.kt
> +class PinedMessageModel
Pinned

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/presentation/feature/pined_message_viewer/PinedMessageModel.kt
> +                downloadedFail = {
downloadFailed

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/presentation/helper/file_viewer_helper/FileViewerHelper.kt
> +        const val DOCUMENTS_LIMIT = 99
норм такое будет?

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/presentation/helper/file_viewer_helper/gellery/TakePicture.kt
> +
пробелы пустые

2025-02-04 16:47 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/data/local/db/entity/settings/SettingFromServerJSON.kt
> -    var webchat_version: WebchatVersion? = WebchatVersion(null,null, null)
а почему файл в 2 раза уменьшился?

2025-02-05 08:41 UTC, anclyakeks commented on chat/src/main/java/com/crafttalk/chat/domain/interactors/AuthInteractor.kt
> +
Ты уверен что все кейсы обрабатываются?
Если нет, судя по оставленным строкам я бы добавил лог, если вдруг другое что-то попадёт сюда, хотя бы комменатрий что это для дальнейшего расширения

Плюсом у тебя else -> не приведены к единому стилю

2025-02-05 08:49 UTC, anclyakeks commented on chat/src/main/java/com/crafttalk/chat/data/repository/PersonRepository.kt
> +                Log.e("CTALK_FAIL_REQUEST","Undefined behavior detected, please investigate the issue")
Лог явно не указывает на ошибку

2025-02-05 09:00 UTC, anclyakeks commented on app/src/main/java/com/crafttalk/sampleChat/web_view/WebViewActivity.kt
> +        loadDataWithBaseURL("${getString(R.string.webUrlChatScheme)}://${getString(R.string.webUrlChatHost)}/webchat/${getString(R.string.webUrlChatNameSpace)}",script,"text/html","UTF-8", null)
Разгрузи функцию
val link = "..."
loadDataWithBaseURL(link...)

2025-02-13 17:03 UTC, Netlighter commented on chat/src/main/java/com/crafttalk/chat/domain/interactors/FileInteractor.kt
> +        downloadedFailed: () -> Unit
downloadFailed :D

2025-02-18 08:09 UTC, lyaskovskii commented on chat/src/main/java/com/crafttalk/chat/domain/interactors/AuthInteractor.kt
> +                else -> {}
А нужен ли пустой else?

2025-02-18 08:09 UTC, lyaskovskii commented on chat/src/main/java/com/crafttalk/chat/domain/interactors/AuthInteractor.kt
> +            else -> {
Пустой else

2025-02-18 08:10 UTC, lyaskovskii commented on chat/src/main/java/com/crafttalk/chat/presentation/feature/view_picture/ShowMediaDialog2.kt
> +//import kotlinx.android.synthetic.main.activity_show_media_dialog2.image_show
Может удалить закомменченный код во всем мре?

2025-02-18 08:11 UTC, lyaskovskii commented on chat/src/main/java/com/crafttalk/chat/presentation/helper/extensions/ImageView.kt
> +            else ->{}
Может логов хотя бы напихать в пустые блоки else?

2025-02-19 08:14 UTC, merged